version: '2.5'
services:
    rest:
      image: perm_rest:latest
      ports:
        - "8560:8560"
      volumes:
        - ./online_predictor/models:/app/models

    predictor:
      image: perm_predictor:latest
      volumes:
        - ./online_predictor/models:/app/models
        - ./online_predictor/Clickhouse_load.py:/app/Clickhouse_load.py
        - ./online_predictor/tasks_pnos.json:/app/tasks_pnos.json
        - ./predictApp_pnos.log:/root/predictApp_pnos.log

    clickhouse-server:
     image: clickhouse/clickhouse-server:22.1.4.30
     ports:
     - "8123:8123"
     - "9000:9000"
     - "9009:9009"
     volumes:
         - ./clickhouse/data:/var/lib/clickhouse
         - ./clickhouse/logs:/var/log/clickhouse-server
         - ./clickhouse/etc/config.xml:/etc/clickhouse-server/config.xml
         - ./clickhouse/etc/users.xml:/etc/clickhouse-server/users.xml

    grafana:
      image: grafana/grafana:8.4.4-ubuntu
      volumes:
        - ./grafana/etc:/etc/grafana/
        - ./grafana/data/plugins:/var/lib/grafana/plugins
        - ./grafana/data:/var/lib/grafana/
      ports:
        - 3000:3000
      depends_on:
        - clickhouse-server